Add Devise
AymanJabr/Members-Only-Rails pull request #1
Opened 2021-03-22 12:55 UTC by AymanJabr

2021-03-23 16:44 UTC, afanimartin requested changes
## Changes Required 🙏🏿 
Nice work on the project. You made quite a progress. Most requirements have been fulfilled. Let's make some changes before merging this PR.
- [ ] Update the readme file. I left some comments.
- [ ] Add the sign in/sign out links to the `application.html.erb` layout. This is because these links are repeated in every page on in the app.

### Martin Afani
#### Slack: whiz25

2021-03-23 16:44 UTC, afanimartin commented on README.md
> +3. Download the proper branch git checkout members-only
- I think you mean checkout the `feature/members-only` branch. Please make your instructions clear enough for the user.

2021-03-23 16:44 UTC, afanimartin commented on README.md
> +2. Enter the project folder cd members-only
- Is the folder not named `Members-Only-Rails`?

2021-03-23 16:44 UTC, afanimartin commented on README.md
> +6. Migrate the database using the command 'rake db:migrate'
- Also add command to run `yarn` to prevent the error: `Webpacker::Manifest::MissingEntryError in Devise::Sessions#new `
- Add command for starting the rails server. This should be run after running `yarn`

2021-03-23 16:44 UTC, afanimartin commented on README.md
> +## Instructions
- Add a section for `Built with` to add a list of stacks used in the project. Refer to this [template](https://github.com/microverseinc/readme-template)

2021-03-23 21:22 UTC, jubaan requested changes
[![Microverse][microverse-shield]][microverse-url]
<div>
<h1 align="center"> ⚠️ 🛠️ ⚠️ 🛠️ Changes Required 🛠️ ⚠️ 🛠️ ⚠️ </h1>
<br />
<p><b>"Fail fast, fail often"</b> and don't let this discourage you, because <b>only by failing do we learn to succeed</b>.</p>
<details open="open">
  <summary>Review Summary</summary>
  <ol>
    <li><a href="#congrats"> 💯 Awesome work 👏🏼 👏🏼 </a></li>
    <li><a href="#mandatory"> ⚠️ Things to Improve </a> 🚨 🚨 </li>
    <li><a href="#optional"> 💡Nice to have and other comments ✍🏼 ✍🏼 </a></li>
    <li><a href="#contact"> 🧔🏼 About your Reviewer </a> (you don't know it... but we are just automated bots 🤖) </li>
    <li><a href="#help"> 🆘 <b> 😭 Feeling stuck? or Need help</b>? 🙏🏼 🙏🏼 </a></li>
  </ol>
</details>
</div>

<h3 id="congrats"> 1. :100: Awesome work</h3>
<details close="close">
<summary> [click to open] Big or little achievements, but achievements at the end. <b>Feel proud that you're learning and improving everyday.</b></summary>
<!-- BEGIN Awesome work -->

<!-- END Awesome work  -->
</details>

<hr>
<h3 id="mandatory"> 2. ⚠️ Things to Improve (or the To-Do list to get the project approved) </h3> 
<details close="close">
<summary> [click to open] Working on these observations will help you advance and get closer to the goal 🎯, postpone them or do them half-ways and they'll haunt you 👻 👻... FOREVER!! (It will feel like that, trust me). </summary>
<!-- BEGIN Review -->

- [ ] Please review the previous feedback and work on it.
- [ ] The README is not professional
- [ ] The MIT license link takes to someone else MIT License (your giving credit for your project to someone else)
- [ ] do not use SocialMedia Handlers, use your actual Social media user name. Example: BAD [GitHubHandler](#) GOOD [@jubaan](https://www.github.com/jubaan)


<!-- END Review -->
</details>
<p><b>NOTE</b>This list is or could be divided in what is show in this comment and inline comments posted below.<p>
<hr>

<h3 id="optional"> 3. 💡 Nice to have and other comments </h3>
<details close="close">
<summary> [click to open] </h3></summary>
<!-- BEGIN Optional and Comments -->

- [x] Nothing more to add.

<!-- END Optional and Comments -->
</details>

<h3 id="contact"> 4. 🧔🏼 About your Reviewer </h3>
<details close="close">
<summary> [click to open] Say "hello world!" on Slack: @jubaan</summary>
<br />
<div align="center">
  <a src="https://www.github.com/jubaan">
    <img src="https://avatars.githubusercontent.com/u/25774518?s=400&u=ae20ddf2d6fb3cae9e2f4044afe3b93d19e5b69e&v=4" alt="Julio Añoveros" title="@jubaan" width="100px" heigh="100px"/>
  </a>
  <p>
    Julio Añoveros | @jubaan</br></br>
    <b>Full-stack Web Developer</b> and</br>
    🤖 Code Reviewer at <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a>:rocket:
  </p>
</div>
</details>

<h3 id="help"> 5. 🆘 <b> 😭 Feeling stuck? or Need help</b>? 🙏🏼 🙏🏼</h3>
<details close="close">
  <summary> [click to open] <b>Feel stuck?</b> </summary>
  <br>
  <p> First breath... just do it. Take 15-20 min away from the computer, stretch, meditate, do some exercise, drink water, or do whatever is necessary to distract your mind from the obstacle.</p>
  <p><b>Sometimes you just need to get away to see things with a new perspective.</b></p>
</details>

<details close="close">
  <summary> [click to open] <b>Need help?</b> </summary>
  <br>
  <p> Send me a DM in <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a> Students Slack, you'll find me as @jubaan. If I'm not available there are other Code Reviewers you can contact. They'll help as well.</p>
  <p>Remember that <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a> has other channels where you can get an answer to your questions:</p>
  <ol>
    <li>The <b>students channel 🧑‍🎓 </b> in slack,</li>
    <li>your <b>teammates 👥 </b>,</li>
    <li>your <b>mentor 👨🏼 👩🏼 </b>, and</li>
    <li><b>Student Success 🏫 </b>.</li>
  </ol>
  <p><b> DON'T hesitate to ask! </b></p>
</details>
<p>If all of the above doesn't help... get a <a href="https://rubberduckdebugging.com/">rubber duck</a> <img src="https://www.pinclipart.com/picdir/big/130-1305924_rubber-ducky-clipart-eastern-iowa-duck-race-duck.png" width="18px" height="18px">... it would be great to own one 😄. </p>

<h2 align="center"> Keep up the great work :muscle: and Happy Coding :smiley: :computer:!! </h1>

[microverse-shield]: https://img.shields.io/badge/-microverse-%236F23FF?style=for-the-badge
[microverse-url]: https://www.microverse.org/?grsf=kfm2ej
[bootstrap-shield]: https://img.shields.io/badge/Bootstrap-white?style=for-the-badge&logo=bootstrap
[bootstrap-url]: https://www.microverse.org/?grsf=kfm2ej

2021-03-24 07:07 UTC, AymanJabr commented on README.md
> +2. Enter the project folder cd members-only
The folder is named members-only

2021-03-24 15:54 UTC, rindrajosia requested changes
Changes Required :red_circle:
To Highlight: :angel:

- [x] The application uses the devise gem for authentication  :+1: 
- [x] The User has*many posts * :muscle: 
- [x] It creates the application routes using resources :posts, only: [:new, :create, :index] :100: 

To Improve :factory_worker:

- [ ] It will be nice when user open your app and will be redirected to the sign in page instead of to be redirected to the default rails home page.
- [ ]  As I can see, your inline comments are helpful and make your code easy to read, but I suggest you focus on your code and logic. Using git history can help us to understand what you have done and  to review a previous version of your code, please, feel free to remove them.
- [ ] It will be perfect if you remove also logic in your view and partial files and put it in your helpers. As a developer your job is to create quality code that solves your client’s problems. Quality has many aspects to it, including readability and maintainability. It is much easier to read code that is lean and skinny, as well as serving a single purpose. When you look at a CSS file, you know it’s for styling and giving your site personality and uniqueness. When you look at a JavaScript file, you know it handles the interactivity on the front-end for the person viewing the site. And the view file is responsible for the HTML.

Nice to have

- [ ]  It displays Flash messages for unsuccessful actions

That's it, you can submit another code review request after making these changes ;recycle: :innocent:
With all my respect :pray:
Rindra Josia

2021-03-24 22:27 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

#### You've done an awesome job so far 👌. But there are still some changes that are necessary for this project to be approved.

- [ ] You still have some logic in your views. There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright)
I have gone ahead and made some comments on your codebase see affected files below:

**Don't know where to start or how to?** See  [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4) 

- [ ] [OPTIONAL]  I see alot of the code in almost every file. Simply removing the `# frozen_string_literal: true` should do instead adding rubocop:disable.
```ruby
# rubocop:disable Style/FrozenStringLiteralComment
# frozen_string_literal: true
```

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2021-03-24 22:27 UTC, acushlakoncept commented on app/views/layouts/application.html.erb
>      <%= yield %>
There should be absolutely NO logic in views.

2021-03-24 22:27 UTC, acushlakoncept commented on app/views/posts/index.html.erb
> +      <%end %>
There should be absolutely NO logic in views.

2021-03-25 07:50 UTC, mimipeshy commented
#### STATUS: APPROVED :dancing_women: :partying_face:
Hello team @AymanJabr and @afanimartin  👋🏾 👋🏾 congratulations on making it far in this project

#### Highlights :white_check_mark: :white_check_mark:
- [ ]  Your have worked on TSE changes required of you
- [ ] Your PR description is well written 
- [ ] Your README file is well written

With that, I approve of this project. All the best in the next projects :technologist:
Regards
Peris Ndanu

2021-03-25 08:32 UTC, merged